### ISSUE TITLE
Google Pixel 7 Pro with 2.0.0 cannot found devices.

### ISSUE THREAD

**Issue by julianLight** [Skyost/Bonsoir#60]
**Describe the bug**
Pixel 7 Pro never found bonjour service.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Android 14
 - bonsoir version: "bonsoir: ^2.0.0"

**Additional context**
There is sample code in my app.

`
BonsoirDiscovery _discovery = BonsoirDiscovery(type: "_dp_Example._tcp.");
await _discovery.ready;
await _discovery.start();
_discovery.eventStream?.listen((BonsoirDiscoveryEvent event) async {
    debugPrint('bonjour. type: ${event.type}, service: ${event.service}, isResolved: ${event.isServiceResolved}.');
    if (event.type == BonsoirDiscoveryEventType.discoveryServiceResolved) {
      final service = event.service;
      _action(service);
    }
}, onError: (e) {
      debugPrint(e.toString());
});
`

The debugPrint only print: bonjour. type: BonsoirDiscoveryEventType.discoveryStarted, service: null, isResolved: false. Even other devices can correctly catch right services.

**Comment by Skyost** [comment]
Ran some tests today on my Google Pixel 7 on the master branch and found no problem so far. Could you please try it ?

In your `pubspec.yaml` :

```yaml
dependency_overrides:
  bonsoir:
    git:
      url: https://github.com/Skyost/Bonsoir.git
      ref: darwin-network
      path: bonsoir
  bonsoir_android:
    git:
      url: https://github.com/Skyost/Bonsoir.git
      ref: darwin-network
      path: bonsoir_android
  bonsoir_darwin:
    git:
      url: https://github.com/Skyost/Bonsoir.git
      ref: darwin-network
      path: bonsoir_darwin
  bonsoir_platform_interface:
    git:
      url: https://github.com/Skyost/Bonsoir.git
      ref: darwin-network
      path: bonsoir_platform_interface
```
